src/main/java/entities/SaccoLedgers.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import controllers.util.AppConstants;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import org.eclipse.persistence.annotations.Cache;

/**
 *
 * @author francis
 */
@Cache(alwaysRefresh = true)
@Entity
@Table(name = "sacco_ledgers")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "SaccoLedgers.findAll", query = "SELECT s FROM SaccoLedgers s"),
    @NamedQuery(name = "SaccoLedgers.findById", query = "SELECT s FROM SaccoLedgers s WHERE s.id = :id"),
    @NamedQuery(name = "SaccoLedgers.findByName", query = "SELECT s FROM SaccoLedgers s WHERE s.name = :name"),
    @NamedQuery(name = "SaccoLedgers.findByDescription", query = "SELECT s FROM SaccoLedgers s WHERE s.description = :description")})
public class SaccoLedgers implements Serializable {

    @Basic(optional = false)
    @NotNull
    @Column(name = "is_credit")
    private boolean isCredit;
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "name")
    private String name;
    @Size(max = 45)
    @Column(name = "description")
    private String description;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "ledgerId")
    private Collection<SaccoLedgerEntries> saccoLedgerEntriesCollection;

    public SaccoLedgers() {
    }

    public SaccoLedgers(Integer id) {
        this.id = id;
    }

    public SaccoLedgers(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @XmlTransient
    public Collection<SaccoLedgerEntries> getSaccoLedgerEntriesCollection() {
        ArrayList<SaccoLedgerEntries> list = new ArrayList<>();
        if (saccoLedgerEntriesCollection != null) {
            for (SaccoLedgerEntries sle : saccoLedgerEntriesCollection) {
                if (sle.getIsGeneral() || !sle.getStatusBilled()) {
                    list.add(sle);
                }
            }
        }
        return list;
    }

    public void setSaccoLedgerEntriesCollection(Collection<SaccoLedgerEntries> saccoLedgerEntriesCollection) {
        this.saccoLedgerEntriesCollection = saccoLedgerEntriesCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof SaccoLedgers)) {
            return false;
        }
        SaccoLedgers other = (SaccoLedgers) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entities.SaccoLedgers[ id=" + id + " ]";
    }

    public int getCr() {
        if (getIsCredit()) {
            int total = 0;
            if (getSaccoLedgerEntriesCollection() != null) {
                for (SaccoLedgerEntries sle : getSaccoLedgerEntriesCollection()) {
                    if ((!sle.getStatusBilled() && !sle.getIsGeneral()) || (sle.getIsGeneral())) {
                        total += sle.getCr() - sle.getDr();
                    }
                }
            }
            return total;
        } else {
            return 0;
        }
    }

    public int getDr() {
        if (!getIsCredit()) {
            int total = 0;
            if (getSaccoLedgerEntriesCollection() != null) {
                for (SaccoLedgerEntries sle : getSaccoLedgerEntriesCollection()) {
                    if ((!sle.getStatusBilled() && !sle.getIsGeneral()) || (sle.getIsGeneral())) {
                        total += sle.getDr() - sle.getCr();
                    }
                }
            }
            return total;
        } else {
            return 0;
        }
    }

    public boolean getIsCredit() {
        return isCredit;
    }

    public void setIsCredit(boolean isCredit) {
        this.isCredit = isCredit;
    }

    public int getTotalUnbilled() {
        int total = 0;
        if (getSaccoLedgerEntriesCollection() != null) {
            for (SaccoLedgerEntries sle : getSaccoLedgerEntriesCollection()) {
                if (!sle.getStatusBilled() && !sle.getIsGeneral()) {
                    total += sle.getCr();
                    AppConstants.logger("total credit" + total);
                }
            }

        }
        return total;
    }
    public int getTotalUnbilledDr() {
        int total = 0;
        if (getSaccoLedgerEntriesCollection() != null) {
            for (SaccoLedgerEntries sle : getSaccoLedgerEntriesCollection()) {
                if (!sle.getStatusBilled() && !sle.getIsGeneral()) {
                    total += sle.getDr();
                    AppConstants.logger("total debit" + total);
                }
            }

        }
        return total;
    }
}

src/main/java/controllers/SaccoLedgersController.java
package controllers;

import controllers.util.AppConstants;
import controllers.util.JsfUtil;
import controllers.util.JsfUtil.PersistAction;
import entities.ExpensesCategory;
import entities.SaccoLedgers;
import facades.SaccoLedgersFacade;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.inject.Named;
import org.joda.time.DateTime;

@Named("saccoLedgersController")
@SessionScoped
public class SaccoLedgersController implements Serializable {

    @EJB
    private facades.SaccoLedgersFacade ejbFacade;
    private List<SaccoLedgers> items = null;
    private SaccoLedgers selected;

    public SaccoLedgersController() {
    }

    public SaccoLedgers getSelected() {
        return selected;
    }

    public void setSelected(SaccoLedgers selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private SaccoLedgersFacade getFacade() {
        return ejbFacade;
    }

    public SaccoLedgers prepareCreate() {
        selected = new SaccoLedgers();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("SaccoLedgersCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("SaccoLedgersUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("SaccoLedgersDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void copy()
    {
        for(SaccoLedgers sl:getItems())
        {
            ExpensesCategory exp=new ExpensesCategory();
            exp.setDescription("");
            exp.setTitle(sl.getName());
            getFacade().storeE(exp);
        }
    }
    public void moveAll()
    {
        for(SaccoLedgers sl:getItems())
        {
            AppConstants.logger("merged");
            sl.setId(sl.getId()+50);
            getFacade().editSl(sl);
        }
    }
    public List<SaccoLedgers> getItems() {
        items = getFacade().findAll();
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public SaccoLedgers getSaccoLedgers(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<SaccoLedgers> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<SaccoLedgers> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = SaccoLedgers.class)
    public static class SaccoLedgersControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            SaccoLedgersController controller = (SaccoLedgersController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "saccoLedgersController");
            return controller.getSaccoLedgers(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof SaccoLedgers) {
                SaccoLedgers o = (SaccoLedgers) object;
                return getStringKey(o.getId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), SaccoLedgers.class.getName()});
                return null;
            }
        }

    }
    public int getTotalCredits()
    {
        int total=0;
        if(getItems()!=null)
        {
           for(SaccoLedgers sl:getItems())
           {
               total+=sl.getCr();
           }
        }
        return total;
    }
    public int getTotalDebits()
    {
        int total=0;
        if(getItems()!=null)
        {
           for(SaccoLedgers sl:getItems())
           {
               total+=sl.getDr();
           }
        }
        return total;
    }

    public String getTitle() {
        return "TKN Sacco Trial Balance As At " + new SimpleDateFormat("MMMM-yyyy").format(new DateTime().minusMonths(1).toDate()).replace("-", " Year ");
    }
}

src/main/webapp/admin/saccoLedgers/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="SaccoLedgersCreateDlg" widgetVar="SaccoLedgersCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateSaccoLedgersTitle}">
            <h:form id="SaccoLedgersCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{saccoLedgersController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateSaccoLedgersLabel_id}" for="id" />
                        <p:inputText id="id" value="#{saccoLedgersController.selected.id}" title="#{bundle.CreateSaccoLedgersTitle_id}" required="true" requiredMessage="#{bundle.CreateSaccoLedgersRequiredMessage_id}"/>
                        <p:outputLabel value="#{bundle.CreateSaccoLedgersLabel_name}" for="name" />
                        <p:inputText id="name" value="#{saccoLedgersController.selected.name}" title="#{bundle.CreateSaccoLedgersTitle_name}" required="true" requiredMessage="#{bundle.CreateSaccoLedgersRequiredMessage_name}"/>
                        <p:outputLabel value="#{bundle.CreateSaccoLedgersLabel_description}" for="description" />
                        <p:inputText id="description" value="#{saccoLedgersController.selected.description}" title="#{bundle.CreateSaccoLedgersTitle_description}" />
                    </p:panelGrid>
                    <p:commandButton actionListener="#{saccoLedgersController.create}" value="#{bundle.Save}" update="display,:SaccoLedgersListForm:datalist,:growl" oncomplete="handleSubmit(args,'SaccoLedgersCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="SaccoLedgersCreateDialog.hide()" immediate="true"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/admin/saccoLedgers/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="SaccoLedgersEditDlg" widgetVar="SaccoLedgersEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditSaccoLedgersTitle}">
            <h:form id="SaccoLedgersEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{saccoLedgersController.selected != null}">
                        <p:outputLabel value="#{bundle.EditSaccoLedgersLabel_id}" for="id" />
                        <p:inputText id="id" value="#{saccoLedgersController.selected.id}" title="#{bundle.EditSaccoLedgersTitle_id}" required="true" requiredMessage="#{bundle.EditSaccoLedgersRequiredMessage_id}"/>
                        <p:outputLabel value="#{bundle.EditSaccoLedgersLabel_name}" for="name" />
                        <p:inputText id="name" value="#{saccoLedgersController.selected.name}" title="#{bundle.EditSaccoLedgersTitle_name}" required="true" requiredMessage="#{bundle.EditSaccoLedgersRequiredMessage_name}"/>
                        <p:outputLabel value="#{bundle.EditSaccoLedgersLabel_description}" for="description" />
                        <p:inputText id="description" value="#{saccoLedgersController.selected.description}" title="#{bundle.EditSaccoLedgersTitle_description}" />
                    </p:panelGrid>
                    <p:commandButton actionListener="#{saccoLedgersController.update}" value="#{bundle.Save}" update="display,:SaccoLedgersListForm:datalist,:growl" oncomplete="handleSubmit(args, 'SaccoLedgersEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="SaccoLedgersEditDialog.hide()" immediate="true"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/admin/saccoLedgers/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/admin/template/main.xhtml">


        <ui:define name="title">
            <h:outputText value="Trial Balance"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <!-- Page Heading -->
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        Trial Balance  <small> Trial Balance</small>
                    </h1>
                </div>
            </div>
            <!-- /.row -->
            <!-- /.row -->
            <div class="row">
                <div class="col-md-12">
                    <p:messages id="growl" closable="true" />
                </div>
            </div>
            <h:form id="SaccoLedgersListForm">
                <!--<p:commandButton actionListener="#{saccoLedgersController.copy()}"/>-->
                <p:panel header="#{saccoLedgersController.title}">
                    <p:dataTable id="datalist" value="#{saccoLedgersController.items}" var="item"
                                 rowKey="#{item.id}"
                                 rowIndexVar="rowIndex"
                                 >
                        <p:column style="width: 30px">
                            <f:facet name="header">
                                <h:outputText value="NO."/>
                            </f:facet>
                            <h:outputText value="#{rowIndex+1}"/>                        
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSaccoLedgersTitle_name}"/>
                            </f:facet>
                            <h:outputText value="#{item.name}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Dr"/>
                            </f:facet>
                            <h:outputText value="#{item.dr}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Cr"/>
                            </f:facet>
                            <h:outputText value="#{item.cr}"/>
                        </p:column>
                        <p:columnGroup type="footer">
                        <p:row>
                            <p:column footerText=""/>
                            <p:column footerText="Total"/>
                            <p:column footerText="#{saccoLedgersController.totalDebits}"/>
                            <p:column footerText="#{saccoLedgersController.totalCredits}"/>
                        </p:row>
                    </p:columnGroup>
                    </p:dataTable>
                </p:panel>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/admin/saccoLedgers/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="SaccoLedgersViewDlg" widgetVar="SaccoLedgersViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewSaccoLedgersTitle}">
            <h:form id="SaccoLedgersViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{saccoLedgersController.selected != null}">
                        <h:outputText value="#{bundle.ViewSaccoLedgersLabel_id}"/>
                        <h:outputText value="#{saccoLedgersController.selected.id}" title="#{bundle.ViewSaccoLedgersTitle_id}"/>
                        <h:outputText value="#{bundle.ViewSaccoLedgersLabel_name}"/>
                        <h:outputText value="#{saccoLedgersController.selected.name}" title="#{bundle.ViewSaccoLedgersTitle_name}"/>
                        <h:outputText value="#{bundle.ViewSaccoLedgersLabel_description}"/>
                        <h:outputText value="#{saccoLedgersController.selected.description}" title="#{bundle.ViewSaccoLedgersTitle_description}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="SaccoLedgersViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>