src/main/java/entities/Loan.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import controllers.util.AppConstants;
import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import org.eclipse.persistence.annotations.Cache;

/**
 *
 * @author francis
 */
@Cache(alwaysRefresh = true)
@Entity
@Table(name = "loan")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Loan.findAll", query = "SELECT l FROM Loan l"),
    @NamedQuery(name = "Loan.findByLoanId", query = "SELECT l FROM Loan l WHERE l.loanId = :loanId"),
    @NamedQuery(name = "Loan.findByDuration", query = "SELECT l FROM Loan l WHERE l.duration = :duration"),
    @NamedQuery(name = "Loan.findByIssueDate", query = "SELECT l FROM Loan l WHERE l.issueDate = :issueDate"),
    @NamedQuery(name = "Loan.findByAmount", query = "SELECT l FROM Loan l WHERE l.amount = :amount"),
    @NamedQuery(name = "Loan.findByInterestRate", query = "SELECT l FROM Loan l WHERE l.interestRate = :interestRate")})
public class Loan implements Serializable {

    @Basic(optional = false)
    @NotNull
    @Column(name = "loan_status")
    private boolean loanStatus;

    @Basic(optional = false)
    @NotNull
    @Column(name = "stop_billing")
    private boolean stopBilling;

    @Basic(optional = false)
    @NotNull
    @Column(name = "pedding")
    private boolean pedding;

    @Basic(optional = false)
    @NotNull
    @Column(name = "grace_period_count")
    private int gracePeriodCount;

    @Basic(optional = false)
    @NotNull
    @Column(name = "deffault_count")
    private int deffaultCount;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "loanId")
    private Collection<LoanRecovery> loanRecoveryCollection;

    @Basic(optional = false)
    @NotNull
    @Column(name = "negotiation_fee")
    private int negotiationFee;
    @JoinColumn(name = "loantype", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private LoanTypes loantype;
    @Basic(optional = false)
    @NotNull
    @Column(name = "random_int")
    private int randomInt;
    @Basic(optional = false)
    @NotNull
    @Column(name = "issue_date")
    @Temporal(TemporalType.DATE)
    private Date issueDate = new Date();
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "loan_id")
    private Integer loanId;
    @Basic(optional = false)
    @NotNull
    @Column(name = "duration")
    private int duration = 36;
    @Basic(optional = false)
    @NotNull
    @Column(name = "amount")
    private double amount;
    @Basic(optional = false)
    @NotNull
    @Column(name = "interest_rate")
    private double interestRate;
    @JoinColumn(name = "memeber_id", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private Members memeberId;
    @OneToMany(mappedBy = "loanId")
    private Collection<LoanSchedules> loanSchedulesCollection;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "loanId")
    private Collection<Guarantors> guarantorsCollection;

    public Loan() {
    }

    public Loan(Integer loanId) {
        this.loanId = loanId;
    }

    public Loan(Integer loanId, int duration, Date issueDate, double amount, double interestRate) {
        this.loanId = loanId;
        this.duration = duration;
        this.issueDate = issueDate;
        this.amount = amount;
        this.interestRate = interestRate;
    }

    public Integer getLoanId() {
        return loanId;
    }

    public void setLoanId(Integer loanId) {
        this.loanId = loanId;
    }

    public int getDuration() {
        return duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public double getInterestRate() {
        return interestRate;
    }

    public void setInterestRate(double interestRate) {
        this.interestRate = interestRate;
    }

    public Members getMemeberId() {
        return memeberId;
    }

    public void setMemeberId(Members memeberId) {
        this.memeberId = memeberId;
    }

    @XmlTransient
    public Collection<LoanSchedules> getLoanSchedulesCollection() {
        return loanSchedulesCollection;
    }

    public void setLoanSchedulesCollection(Collection<LoanSchedules> loanSchedulesCollection) {
        this.loanSchedulesCollection = loanSchedulesCollection;
    }

    @XmlTransient
    public Collection<Guarantors> getGuarantorsCollection() {
        return guarantorsCollection;
    }

    public void setGuarantorsCollection(Collection<Guarantors> guarantorsCollection) {
        this.guarantorsCollection = guarantorsCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (loanId != null ? loanId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Loan)) {
            return false;
        }
        Loan other = (Loan) object;
        if ((this.loanId == null && other.loanId != null) || (this.loanId != null && !this.loanId.equals(other.loanId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Loan{" + "deffaultCount=" + deffaultCount + ", negotiationFee=" + negotiationFee + ", loantype=" + loantype + ", loanId=" + loanId + ", loanSchedulesCollection=" + loanSchedulesCollection + '}';
    }

    public Date getIssueDate() {
        return issueDate;
    }

    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }

    public int getRandomInt() {
        return randomInt;
    }

    public void setRandomInt(int randomInt) {
        this.randomInt = randomInt;
    }

    public LoanSchedules getCurrentSchedule() {
        if (getLoanSchedulesCollection() != null) {
            for (LoanSchedules schedule : getLoanSchedulesCollection()) {
                if (schedule.getStatusCleared().getStatus().equalsIgnoreCase("Current")) {
                    return schedule;
                }
            }
        }
        return new LoanSchedules();
    }

    public LoanTypes getLoantype() {
        return loantype;
    }

    public void setLoantype(LoanTypes loantype) {
        this.loantype = loantype;
    }

    public int getBalEst() {
        if (!getLoanStatus()) {
            if (getLoantype() != null) {
                if (getLoantype().getId() == 1) {
                    if (!getPedding() && getMemeberId().hasPendingEmergency()) {
                        AppConstants.logger("has pending:");
                        return 0;
                    } else if (!getPedding() && !getMemeberId().hasPendingEmergency()) {
                        return getMemeberId().getEstimatedLoanBalanceEmergency();
                    } else {
                        AppConstants.logger("getMemeberId().getBalanceForPendingLoanEmergency()---:" + getMemeberId().getBalanceForPendingLoanEmergency());
                        AppConstants.logger("getCollected()---:" + getCollected());
                        return (int) (Math.floor((getMemeberId().getBalanceForPendingLoanEmergency() - getCollectedActual())));
                    }
                } else if (!getLoanStatus() && getLoantype().getId() == 2) {
                    if (!getPedding() && getMemeberId().hasPendingNormal()) {
                        AppConstants.logger("has pending:");
                        return 0;
                    } else if (!getPedding() && !getMemeberId().hasPendingNormal()) {
                        AppConstants.logger("has no pending:");
                        return getMemeberId().getEstimatedLoanBalanceNormal();
                    } else {
                        AppConstants.logger("calc");

                        return (int) (Math.floor((getMemeberId().getBalanceForPendingLoanNormal() - getCollectedActual())));
                    }
                }
            }
        }
        return 0;
    }

    public int getBalEstWithoutInterest() {
        if (!getLoanStatus() && getLoantype().getId() == 1) {
            if (!getPedding() && getMemeberId().hasPendingEmergency()) {
                return 0;
            } else if (!getPedding() && !getMemeberId().hasPendingEmergency()) {
                return getMemeberId().getEstimatedLoanBalanceEmergencyWithoutInterest();
            } else if (getPedding()) {
                return (int) (Math.floor((getMemeberId().getBalanceForPendingLoanEmergency() - getCollected())));
            }
        } else if (!getLoanStatus() && getLoantype().getId() == 2) {
            if (!getPedding() && getMemeberId().hasPendingNormal()) {
                return 0;
            } else if (!getPedding() && !getMemeberId().hasPendingNormal()) {
                return getMemeberId().getEstimatedLoanBalanceNormalWithoutInterests();
            } else {

src/main/java/entities/LoanTypes.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author francis
 */
@Entity
@Table(name = "loan_types")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "LoanTypes.findAll", query = "SELECT l FROM LoanTypes l"),
    @NamedQuery(name = "LoanTypes.findById", query = "SELECT l FROM LoanTypes l WHERE l.id = :id"),
    @NamedQuery(name = "LoanTypes.findByLoanType", query = "SELECT l FROM LoanTypes l WHERE l.loanType = :loanType")})
public class LoanTypes implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "loan_type")
    private String loanType;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "loantype")
    private Collection<Loan> loanCollection;

    public LoanTypes() {
    }

    public LoanTypes(Integer id) {
        this.id = id;
    }

    public LoanTypes(Integer id, String loanType) {
        this.id = id;
        this.loanType = loanType;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLoanType() {
        return loanType;
    }

    public void setLoanType(String loanType) {
        this.loanType = loanType;
    }

    @XmlTransient
    public Collection<Loan> getLoanCollection() {
        return loanCollection;
    }

    public void setLoanCollection(Collection<Loan> loanCollection) {
        this.loanCollection = loanCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof LoanTypes)) {
            return false;
        }
        LoanTypes other = (LoanTypes) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "LoanTypes{" + "id=" + id + ", loanType=" + loanType + '}';
    }

}

src/main/webapp/admin/loan/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="LoanCreateDlg" widgetVar="LoanCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateLoanTitle}">
            <h:form id="LoanCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{loanController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateLoanLabel_loanId}" for="loanId" />
                        <p:inputText id="loanId" value="#{loanController.selected.loanId}" title="#{bundle.CreateLoanTitle_loanId}" required="true" requiredMessage="#{bundle.CreateLoanRequiredMessage_loanId}"/>
                        <p:outputLabel value="#{bundle.CreateLoanLabel_duration}" for="duration" />
                        <p:inputText id="duration" value="#{loanController.selected.duration}" title="#{bundle.CreateLoanTitle_duration}" required="true" requiredMessage="#{bundle.CreateLoanRequiredMessage_duration}"/>
                        <p:outputLabel value="#{bundle.CreateLoanLabel_issueDate}" for="issueDate" />
                        <p:inputText id="issueDate" value="#{loanController.selected.issueDate}" title="#{bundle.CreateLoanTitle_issueDate}" required="true" requiredMessage="#{bundle.CreateLoanRequiredMessage_issueDate}"/>
                        <p:outputLabel value="#{bundle.CreateLoanLabel_amount}" for="amount" />
                        <p:inputText id="amount" value="#{loanController.selected.amount}" title="#{bundle.CreateLoanTitle_amount}" required="true" requiredMessage="#{bundle.CreateLoanRequiredMessage_amount}"/>
                        <p:outputLabel value="#{bundle.CreateLoanLabel_interestRate}" for="interestRate" />
                        <p:inputText id="interestRate" value="#{loanController.selected.interestRate}" title="#{bundle.CreateLoanTitle_interestRate}" required="true" requiredMessage="#{bundle.CreateLoanRequiredMessage_interestRate}"/>
                        <p:outputLabel value="#{bundle.CreateLoanLabel_memeberId}" for="memeberId" />
                        <p:selectOneMenu id="memeberId" value="#{loanController.selected.memeberId}" required="true" requiredMessage="#{bundle.EditLoanRequiredMessage_memeberId}">
                            <f:selectItems value="#{membersController.itemsAvailableSelectOne}"
                                           var="memeberIdItem"
                                           itemValue="#{memeberIdItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateLoanLabel_loanStatus}" for="loanStatus" />
                        <p:selectOneMenu id="loanStatus" value="#{loanController.selected.loanStatus}" required="true" requiredMessage="#{bundle.EditLoanRequiredMessage_loanStatus}">
                            <f:selectItems value="#{loanStatusController.itemsAvailableSelectOne}"
                                           var="loanStatusItem"
                                           itemValue="#{loanStatusItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{loanController.create}" value="#{bundle.Save}" update="display,:LoanListForm:datalist,:growl" oncomplete="handleSubmit(args,'LoanCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="LoanCreateDialog.hide()" immediate="true"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/admin/loan/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/admin/template/main.xhtml">


        <ui:define name="title">
            <h:outputText value="Loans To Memers"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <!-- Page Heading -->
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        Loans <small>List of Loans to members</small>
                    </h1>
                </div>
            </div>
            <!-- /.row -->
            <!-- /.row -->
            <div class="row">
                <div class="col-md-12">
                    <p:messages id="growl" closable="true" />
                </div>
            </div>
            <h:form id="LoanListForm">
                <p:panel header="#{loanController.title}">
                    <p:dataTable id="datalist" value="#{loanController.items}" var="item"
                                 rowKey="#{item.loanId}"
                                 rowIndexVar="rowIndex"
                                 rowStyleClass="#{item.isDeffaulted le false ?  true: 'coloredloan'}"
                                 >
                        <p:column style="width: 30px">
                            <f:facet name="header">
                                <h:outputText value="NO."/>
                            </f:facet>
                            <h:outputText value="#{rowIndex+1}"/>                        
                        </p:column>
                        <p:column filterBy="#{item.memeberId.trimmedSurname}" sortBy="#{item.memeberId.surname}">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLoanTitle_memeberId}"/>
                            </f:facet>
                            <h:outputText value="#{item.memeberId.surname}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLoanTitle_issueDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.issueDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy" timeZone="Africa/Nairobi" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Loan Type"/>
                            </f:facet>
                            <h:outputText value="#{item.loantype.loanType}"/>
                        </p:column>
                        <p:column filterBy="#{item.statusStr}" >
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLoanTitle_loanStatus}"/>
                            </f:facet>
                            <h:outputText value="#{item.statusStr}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Months Deffaulted"/>
                            </f:facet>
                            <h:outputText value="#{item.deffaultCount}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLoanTitle_amount}"/>
                            </f:facet>
                            <h:outputText value="#{item.amount}"/>
                        </p:column>
                        <p:column filterBy="#{item.balEst}">
                            <f:facet name="header">
                                <h:outputText value="Balance With Interests"/>
                            </f:facet>
                            <h:outputText value="#{item.balEst}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Negotiation Fee"/>
                            </f:facet>
                            <h:outputText value="#{item.negotiationFee}"/>
                        </p:column>                        
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Interest Earned"/>
                            </f:facet>
                            <h:outputText value="#{item.totalInterestEarned}"/>
                        </p:column>
                        <p:columnGroup type="footer">
                            <p:row>
                                <p:column footerText=""/>
                                <p:column footerText=""/>
                                <p:column footerText=""/>
                                <p:column footerText=""/>
                                <p:column footerText=""/>
                                <p:column footerText="Total"/>
                                <p:column footerText="#{loanController.totalLoans}"/>
                                <p:column footerText="#{loanController.totalLoansBalances}"/>  
                                <p:column footerText="#{loanController.totalLoansNegotiation}"/> 
                                <p:column footerText="#{loanController.totalLoansInterest}"/> 
                            </p:row>
                        </p:columnGroup>
                    </p:dataTable>
                </p:panel>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/admin/loan/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="LoanViewDlg" widgetVar="LoanViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewLoanTitle}">
            <h:form id="LoanViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{loanController.selected != null}">
                        <h:outputText value="#{bundle.ViewLoanLabel_loanId}"/>
                        <h:outputText value="#{loanController.selected.loanId}" title="#{bundle.ViewLoanTitle_loanId}"/>
                        <h:outputText value="#{bundle.ViewLoanLabel_duration}"/>
                        <h:outputText value="#{loanController.selected.duration}" title="#{bundle.ViewLoanTitle_duration}"/>
                        <h:outputText value="#{bundle.ViewLoanLabel_issueDate}"/>
                        <h:outputText value="#{loanController.selected.issueDate}" title="#{bundle.ViewLoanTitle_issueDate}"/>
                        <h:outputText value="#{bundle.ViewLoanLabel_amount}"/>
                        <h:outputText value="#{loanController.selected.amount}" title="#{bundle.ViewLoanTitle_amount}"/>
                        <h:outputText value="#{bundle.ViewLoanLabel_interestRate}"/>
                        <h:outputText value="#{loanController.selected.interestRate}" title="#{bundle.ViewLoanTitle_interestRate}"/>
                        <h:outputText value="#{bundle.ViewLoanLabel_memeberId}"/>
                        <h:outputText value="#{loanController.selected.memeberId}" title="#{bundle.ViewLoanTitle_memeberId}"/>
                        <h:outputText value="#{bundle.ViewLoanLabel_loanStatus}"/>
                        <h:outputText value="#{loanController.selected.loanStatus}" title="#{bundle.ViewLoanTitle_loanStatus}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="LoanViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/admin/loan/deffaultedLoans.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/admin/template/main.xhtml">


        <ui:define name="title">
            <h:outputText value="Defaulted Loans"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <!-- Page Heading -->
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        Defaulted Loans <small>List of Defaulted Loans to members</small>
                    </h1>
                </div>
            </div>
            <!-- /.row -->
            <!-- /.row -->
            <div class="row">
                <div class="col-md-12">
                    <p:messages id="growl" closable="true" />
                </div>
            </div>
            <h:form id="LoanListForm">
                    <p:commandButton value="Print">
                        <p:printer target="ct" />
                    </p:commandButton>
                <p:panel header="List of Defaulted Loans to members" id="ct">
                    <p:dataTable id="datalist" value="#{loanController.itemsDefaulted}" var="item"
                                 rowKey="#{item.loanId}"
                                 rowIndexVar="rowIndex"
                                 >
                        <p:column style="width: 30px">
                            <f:facet name="header">
                                <h:outputText value="NO."/>
                            </f:facet>
                            <h:outputText value="#{rowIndex+1}"/>                        
                        </p:column>
                        <p:column style="width: 180px">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLoanTitle_memeberId}"/>
                            </f:facet>
                            <h:outputText value="#{item.memeberId.surname}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLoanTitle_issueDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.issueDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy" timeZone="Africa/Nairobi" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Loan Type"/>
                            </f:facet>
                            <h:outputText value="#{item.loantype.loanType}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLoanTitle_loanStatus}"/>
                            </f:facet>
                            <h:outputText value="#{item.statusStr}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Months Deffaulted"/>
                            </f:facet>
                            <h:outputText value="#{item.deffaultCount}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLoanTitle_amount}"/>
                            </f:facet>
                            <h:outputText value="#{item.amount}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Balance With Interests"/>
                            </f:facet>
                            <h:outputText value="#{item.balEst}"/>
                        </p:column>
                        <p:columnGroup type="footer">
                            <p:row>
                                <p:column footerText=""/>
                                <p:column footerText=""/>
                                <p:column footerText=""/>
                                <p:column footerText=""/>
                                <p:column footerText=""/>
                                <p:column footerText="Total"/>
                                <p:column footerText="#{loanController.totalLoansDefaulted}"/>
                                <p:column footerText="#{loanController.totalLoansBalancesDefaulted}"/>  
                            </p:row>
                        </p:columnGroup>
                    </p:dataTable>
                </p:panel>
            </h:form>
        </ui:define>
    </ui:composition>

</html>